replicaCount: 1

image:
  repository: ghcr.io/roclub/devices-backend
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  kafka:
    bostrapServers: ""
    groupdID: ""
    autoOffsetReset: ""
    enableAutoCommit: ""
    securityProtocol: ""
    saslMechanisms: ""
    pollIntervall: ""
    saslUsername: ""
    saslPassword: ""
    topics: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ""
  tls:
    secretName: ""
    
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
