imagePullSecrets:
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

stage: "dev"

serviceAccount:
  create: true
  annotations: {}
  name: ""

  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  image:
    repository: ghcr.io/roclub/livekit-remote-control-conference-development
    pullPolicy: IfNotPresent
    tag: "0.1.13"
    
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "dev-cluster-bootstrap-traefik"
    annotations:
        cert-manager.io/cluster-issuer: "dev.roclub.io"
    recordName: conference2.dev.roclub.io 
    zoneName: dev.roclub.io.
    stage: dev
    loadBalancerSelector: default/dev-cluster-bootstrap-traefik
    hosts:
    - host: "conference2.dev.roclub.io"
      paths:
        - path: /
          pathType: Prefix
    tls:
      secretName: "conference2-tls"
      hosts: 
      - "conference2.dev.roclub.io"

  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
