apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roclub-app-webrtc-test.fullname" . }}
  labels:
    {{- include "roclub-app-webrtc-test.labels" . | nindent 4 }}
data:
  config.toml: |-
    [app]
    port = {{ .Values.frontend.config.app.port }}
    environment = "{{ .Values.frontend.config.app.environment }}"

    [logger]
    level = "{{ .Values.config.logger }}"

    [aws]
    aws_access_key = "{{ .Values.config.aws.aws_access_key }}"
    aws_secret_key = "{{ .Values.config.aws.aws_secret_key }}"
    aws_s3_bucket = "{{ .Values.config.aws.aws_s3_bucket }}"
    aws_s3_region = "{{ .Values.config.aws.aws_s3_region }}"
