apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roclub-app-webrtc-test.fullname" . }}
  labels:
    {{- include "roclub-app-webrtc-test.labels" . | nindent 4 }}
data:
  config.toml: |-
    [app]
    port = {{ .Values.frontend.config.app.port }}
    environment = "{{ .Values.frontend.config.app.environment }}"

    [logger]
    level = "{{ .Values.config.logger }}"

    [aws]
    aws_access_key = "{{ .Values.backend.config.aws.awsAccessKey }}"
    aws_secret_key = "{{ .Values.backend.config.aws.awsSecretKey }}"
    aws_s3_bucket = "{{ .Values.backend.config.aws.awsS3Bucket }}"
    aws_s3_region = "{{ .Values.backend.config.aws.awsS3Region }}"

    [mongodb]
    connection_string = "{{ .Values.backend.config.mongodb.connectionString }}"
    database = "{{ .Values.backend.config.mongodb.database }}"
    collection = "{{ .Values.backend.config.mongodb.collection }}"
