apiVersion: v1
kind: Service
metadata:
  name: {{ include "roclub-app-org-registration.informationName" . }}
  labels:
    {{- include "roclub-app-org-registration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "roclub-app-org-registration.selectorLabels" . | nindent 4 }}
