{{- $gatewayName := include "controlplane.fullname" . -}}
{{- $name := include "controlplane.conferenceWebsocketName" . -}}
{{- $svcPort := .Values.conferenceWebsocket.service.port -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $gatewayName }}-conference-websocket
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
  hostnames:
  {{- range .Values.recordNames }}
    - {{ . }}
  {{- end }}
  rules:
  {{- range .Values.conferenceWebsocket.gatewayAPI.hosts }}
    - matches:
      {{- range .paths }}
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      {{- end }}
      backendRefs:
        - name: {{ $name }}
          port: {{ $svcPort }}
  {{- end }}

