nameOverride: ""
fullnameOverride: ""

stage: "dev"
recordNames:
  - cp.dev.roclub.io123

authZ:
  service:
    name: ""
    nameByStage:
      dev: dev-controlplane-authz
      stg: stg-controlplane-authz
      prd: prd-controlplane-authz
    port: 8080

conferenceWebsocket:
  image:
    repository: ghcr.io/roclub/conference-websocket-development
    tag: 0.0.2
    pullPolicy: Always

  imagePullSecrets:
    - name: dockerconfigjson-github-com

  replicaCount: 1

  service:
    type: ClusterIP
    port: 8080

  resources: {}

  nodeSelector:
    beta.kubernetes.io/arch: arm64

  tolerations: []
  affinity: {}

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "conference-websocket"

  gatewayAPI:
    hosts:
      - paths:
          - path: /v2/websocket/
            pathType: PathPrefix

  env:
    - name: TOKEN
      value: ""
    - name: ALLOWED_ORIGIN
      value: ""

remoteControl:
  image:
    repository: ghcr.io/roclub/controlplane-session-control
    pullPolicy: Always

  imagePullSecrets: 
    - name: dockerconfigjson-github-com

  replicaCount: 1

  config:
    env: "dev"
    serviceAccounts: []

    iotDataplane:
      key: ""
      secret: ""

    redis:
      enabled: false
      url: ""
      username: ""
      password: ""
      db: 0
      ttlSeconds: 300
      negativeTtlSeconds: 10
      timeoutMs: 2000
      maxRetries: 3

    liveKit:
      key: ""
      secret: ""
      host: ""
      ttl: 300

    logger: "debug"

  service:
    type: ClusterIP
    httpPort: 8081
    gRPCPort: 8080

  gatewayAPI:
    hosts:
      - paths:
          - path: /v2/sessions/
            pathType: PathPrefix

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "remote-control"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

connectorStatus:
  image:
    repository: ghcr.io/roclub/controlplane-connector-status
    pullPolicy: Always

  imagePullSecrets: 
    - name: dockerconfigjson-github-com

  replicaCount: 1

  config:
    env: "dev"
    serviceAccounts: []
    
    kafka:
      bootstrapServers: []
      saslUsername: ""
      saslPassword: ""

    influx:
      org: "roclub"

    logger: "debug"

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "connector-status"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    httpPort: 8081
    gRPCPort: 8080

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  volumeMounts: []

  nodeSelector: {}

  tolerations: []
  
  gatewayAPI:
    hosts:
      - paths:
          - path: /v2/connectors/status/
            pathType: PathPrefix

connectorControl:
  image:
    repository: ghcr.io/roclub/controlplane-connector-control
    pullPolicy: Always

  imagePullSecrets: 
    - name: dockerconfigjson-github-com

  replicaCount: 1

  config:
    env: "dev"
    serviceAccounts: []
    
    iotDataplane:
      key: ""
      secret: ""

    redis:
      enabled: false
      url: ""
      username: ""
      password: ""
      db: 0
      ttlSeconds: 300
      negativeTtlSeconds: 10
      timeoutMs: 2000
      maxRetries: 3

    logger: "debug"

  gatewayAPI:
    hosts:
      - paths:
          - path: /v2/connectors/control/
            pathType: PathPrefix

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "connector-control"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    httpPort: 8081
    gRPCPort: 8080

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []

influxdb2:
  enabled: true

  image:
    tag: 2.7.12-alpine

  adminUser:
    organization: "roclub"
    bucket: "connector-status"
    user: "admin"
    retention_policy: "0s"

  persistence:
    enabled: false
    storageClass: "gp3"
    accessMode: ReadWriteOnce
    size: 50Gi
    mountPath: /var/lib/influxdb2
    subPath: ""

notifications:
  image:
    repository: ghcr.io/roclub/controlplane-notifications
    pullPolicy: Always

  imagePullSecrets: 
    - name: dockerconfigjson-github-com

  replicaCount: 1

  config:
    logger: "debug"

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "notifications"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    httpPort: 8081
    gRPCPort: 8080

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # Additional volumes on the output Deployment definition.
  volumes: []
  volumeMounts: []

  nodeSelector: {}

  tolerations: []
  
  gatewayAPI:
    hosts:
      - paths:
          - path: /v2/notifications/register
            pathType: PathPrefix
          - path: /v2/notifications/vapid
            pathType: PathPrefix

iotKafkaInterfaceCronjob:
  name: iot-kafka-interface-cronjob
  schedule: "*/15 * * * *" # Runs every 15 minutes
  serviceAccount:
    automount: true
    roleArn: arn:aws:iam::172771008158:role/EKSServiceAccountIotKafkaAttachInterfaceRole
  container:
    name: iot-kafka-interface-script-container
    image: ghcr.io/roclub/controlplane-connector-status-interface-script-image:latest
    imagePullPolicy: Always
  imagePullSecrets: dockerconfigjson-github-com
  restartPolicy: OnFailure

redis:
  architecture: "replication"
  auth:
    enabled: true
    sentinel: true
    password: ""
  rbac:
    create: true
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  replica:
    replicaCount: 1
    automountServiceAccountToken: true
    persistence:
      enabled: true
      storageClass: "gp3"
      size: 10Gi
  sentinel:
    enabled: true
    service:
      createMaster: true
    masterService:
      enabled: true
  master:
    persistence:
      enabled: true
      storageClass: "gp3"
      size: 10Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  tls:
    enabled: true
    existingSecret: "controlplane-redis-tls"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    certCAFilename: "ca.crt"
    authClients: false
