apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-operations-platform.remoteOperator" . }}
  labels:
    {{- include "remote-operations-platform.selectorLabelsRemoteOperator" . | nindent 4 }}
spec:
  type: {{ .Values.remoteOperator.service.type }}
  ports:
    - port: {{ .Values.remoteOperator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "remote-operations-platform.selectorLabelsRemoteOperator" . | nindent 4 }}