apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "controlplane-app.fullname" . }}
  labels:
    {{- include "controlplane-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      {{- include "controlplane-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "controlplane-app.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.app.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          command:
            - /usr/local/bin/backend
          args:
            - "--config"
            - "/app/config.yaml"
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane-app.fullname" . }}-pg-runtime
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane-app.fullname" . }}-pg-runtime
                  key: password
          ports:
            - name: grpc
              containerPort: {{ .Values.app.service.gRPCPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.app.service.httpPort }}
              protocol: TCP
          volumeMounts:
            - name: app-config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.app.deployment.resources.requests.cpu }}
              memory: {{ .Values.app.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.deployment.resources.limits.cpu }}
              memory: {{ .Values.app.deployment.resources.limits.memory }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "controlplane-app.fullname" . }}-deployment-config
      nodeSelector:
        {{- toYaml .Values.app.nodeSelector | nindent 8 }}
