apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "controlplane-app.fullname" . }}
  labels:
    {{- include "controlplane-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "controlplane-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "controlplane-app.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/backend
          args:
            - "--config"
            - "/app/config.yaml"
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane-app.fullname" . }}-pg-runtime
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "controlplane-app.fullname" . }}-pg-runtime
                  key: password
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          volumeMounts:
            - name: app-config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "controlplane-app.fullname" . }}-deployment-config
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
