apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "controlplane-app.fullname" . }}-allow-app-ingress
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "controlplane-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "controlplane-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.allowedNamespace | quote }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.allowedPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: http
