apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane-app.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "controlplane-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "controlplane-app.selectorLabels" . | nindent 4 }}
