apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane-app.fullname" . }}
  labels:
    {{- include "controlplane-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.gRPCPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.app.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "controlplane-app.selectorLabelsApp" . | nindent 4 }}
