apiVersion: v2
name: app
description: Deploys the roclub main application to Kubernetes
type: application
version: 0.7.1
appVersion: 0.7.5

dependencies:
  - name: redis
    version: 23.1.1
    repository: https://charts.bitnami.com/bitnami
