imagePullSecrets:
- name: dockerconfigjson-github-com

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources: {}

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector:
  beta.kubernetes.io/arch: arm64 
tolerations: []
affinity: {}

httpRoute:
  enabled: true
  hosts:
    - "app.dev.roclub.io"


cloudfront:
  enabled: false
  cachePolicyId: ""
  originRequestPolicyId: ""
  responseHeadersPolicyId: ""
  hostedZoneId: Z014743627GZM6VTA9N24
  additionalAliases: []
  waf:
    visibility:
      enabled: true
    rules: []

appSecrets:
  authSecret:
    secretKey: ""
  zitadelIssuer:
    secretKey: ""
  zitadelClientId:
    secretKey: ""
  zitadelClientSecret:
    secretKey: ""
  nextauthUrl:
    secretKey: ""
  zitadelBaseUrl:
    secretKey: ""
  zitadelProjectID:
    secretKey: ""
  conferenceProjectID:
    secretKey: ""
  zitadelSaAppCsmUser:
    secretKey: ""
  zitadelSaAppCsmSecret:
    secretKey: ""
  zitadelSaAppAdminUser:
    secretKey: ""
  zitadelSaAppAdminSecret:
    secretKey: ""
  zitadelSaAppDispatcherUser:
    secretKey: ""
  zitadelSaAppDispatcherSecret:
    secretKey: ""
  zitadelSaAppUserUser:
    secretKey: ""
  zitadelSaAppUserSecret:
    secretKey: ""
  zitadelSaControlplaneUser:
    secretKey: ""
  zitadelSaControlplaneSecret:
    secretKey: ""
  zitadelSaAppAdminUserID:
    secretKey: ""
  zitadelSaAppDispatcherUserID:
    secretKey: ""
  zitadelSaAppUserUserID:
    secretKey: ""
  redisEncryptionKey:
    secretKey: ""

image:
  tag: ""
  repository: ghcr.io/roclub/app-development
  pullPolicy: Always
  
replicaCount: 1

service:
  type: ClusterIP
  port: 8080

redis:
  auth:
    enabled: true
    sentinel: true
    password: "ieheithahNue3booqui7eifaoGoo1thahl1oabai"

  architecture: "replication"

  sentinel:
    enabled: true

  tls:
    enabled: true
    existingSecret: "redis-server-tls"
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    certCAFilename: "ca.crt"

  replica:
    # Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if master.resources is set (master.resources is recommended for production).
    resourcesPreset: "nano"
    replicaCount: 1
