apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane-authz.fullname" . }}-config"
  labels:
    {{- include "controlplane-authz.selectorLabelsAuthZ" . | nindent 4 }}
data:
  config.toml: |-
    [authz]
    env = "{{ .Values.config.env }}"
    service_accounts = {{ .Values.config.serviceAccounts }}
    
    [authz.openfga]
    url = "{{ .Values.config.openfga.url }}"
    store_id = "{{ .Values.config.openfga.storeId }}"
    model_id = "{{ .Values.config.openfga.modelId }}"

    [authz.logger]
    level = "{{ .Values.config.logger }}"
