{{- $gatewayName := include "controlplane.fullname" . -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ $gatewayName }}-proxy-config
  namespace: envoy-gateway-system
spec:
  extensionApis:
    enableEnvoyPatchPolicy: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-name: {{ $gatewayName }}
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/service-name={{ $gatewayName }}"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $gatewayName }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    namespace: envoy-gateway-system
    name: {{ $gatewayName }}-proxy-config
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gatewayName }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $gatewayName }}-letsencrypt
spec:
  gatewayClassName: {{ $gatewayName }}
  listeners:
  {{- range .Values.recordNames }}
    - name: {{ . }}-http
      hostname: {{ . }}
      protocol: HTTP
      port: 80
    - name: {{ . }}-https
      hostname: {{ . }}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ . }}-https
  {{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $gatewayName }}-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ""
    email: platformengineering@roclub.com
    privateKeySecretRef:
      name: {{ $gatewayName }}-letsencrypt
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: {{ $gatewayName }}
