{{- $gatewayName := include "controlplane.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $gatewayName}}-cors-preflight
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{.Values.stage }}-controlplane
  hostnames:
  {{- range .Values.recordNames }}
    - {{ . }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{.Values.stage }}-controlplane-remote-control
          port: 8081
          group: ""
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: "/v2/sessions/"
          method: OPTIONS
    - backendRefs:
        - name: {{.Values.stage }}-controlplane-authz
          port: 8081
          group: ""
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: "/v2/authz/"
          method: OPTIONS
    - backendRefs:
        - name: {{.Values.stage }}-controlplane-connector-status
          port: 8081
          group: ""
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: "/v2/connectors/status/"
          method: OPTIONS
    - backendRefs:
        - name: {{.Values.stage }}-controlplane-connector-control
          port: 8081
          group: ""
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: "/v2/connectors/control/"
          method: OPTIONS
    - backendRefs:
        - name: {{.Values.stage }}-controlplane-notifications
          port: 8081
          group: ""
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: "/v2/notifications/"
          method: OPTIONS
    - backendRefs:
        - name: {{.Values.stage }}-controlplane-conference-websocket
          port: 8081
          group: ""
          kind: Service
      matches:
        - path:
            type: PathPrefix
            value: "/v2/websocket/"
          method: OPTIONS
