---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: roclub-pki
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: roclub-pki
spec:
  isCA: true
  commonName: roclub-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: roclub-pki
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: controlplane-redis-tls-ca
spec:
  ca:
    secretName: root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controlplane-redis-tls
spec:
  secretName: controlplane-redis-tls

  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 256

  signatureAlgorithm: ECDSAWithSHA256

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager

  # SANs for controlplane Redis service names.
  dnsNames:
    - {{ .Release.Name }}-redis-headless
    - {{ .Release.Name }}-redis-headless.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Release.Name }}-redis-master
    - {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Release.Name }}-redis-replicas
    - {{ .Release.Name }}-redis-replicas.{{ .Release.Namespace }}.svc.cluster.local

  issuerRef:
    name: controlplane-redis-tls-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controlplane-redis-client-tls
spec:
  secretName: controlplane-redis-client-tls

  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 256

  signatureAlgorithm: ECDSAWithSHA256

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - client auth

  subject:
    organizations:
      - cert-manager

  issuerRef:
    name: controlplane-redis-tls-ca
    kind: Issuer
