apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane.serviceAccountRemoteControlName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  annotations:
spec:
  type: {{ .Values.remoteControl.service.type }}
  ports:
    - port: {{ .Values.remoteControl.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "controlplane.selectorLabels" . | nindent 4 }}
