{{- if .Values.remoteControl.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controlplane.serviceAccountRemoteControlName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  {{- with .Values.remoteControl.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.remoteControl.serviceAccount.automount }}
{{- end }}
