replicaCount: 1

image:
  repository: ghcr.io/roclub/roclub-connector-status
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
environment: ""

config:
  kafka:
    bootstrapServers: []
    groupdID: ""
    autoOffsetReset: ""
    enableAutoCommit: ""
    securityProtocol: ""
    saslMechanisms: ""
    pollIntervall: 10
    saslUsername: ""
    saslPassword: ""
    topics: []

  api:
    bearerToken: ""

  app:
    devicesFolder: ""

  roclubApp:
    webhoookEndpoint: ""
    webhookToken: ""
    webhookTriggerIntervall: 15

  database:
    mongoDBConnectionString: ""

  logging:
    logLevel: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
  - host: ""
    paths:
      - path: /
        pathType: Prefix
  tls:
    hosts: []
    secretName: ""
    clusterIssuer: ""
    
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}