apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "controlplane-app.fullname" . }}-postgres-cluster
  labels:
    {{- include "controlplane-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: {{ .Values.postgres.cluster.instances }}
  description: "controlplane-app Postgres Cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: {{ include "controlplane-app.fullname" . }}-pg-superuser

  bootstrap:
    initdb:
      database: controlplane_app
      owner: {{ .Values.postgres.users.migration }}
      secret:
        name: {{ include "controlplane-app.fullname" . }}-pg-migration

  managed:
    roles:
      - name: {{ .Values.postgres.users.migration }}
        ensure: present
        comment: Schema migration user and owner of the controlplane_app database
        login: true
        superuser: false
        createdb: false
        createrole: false
        replication: false
        bypassrls: false
        passwordSecret:
          name: {{ include "controlplane-app.fullname" . }}-pg-migration
      - name: {{ .Values.postgres.users.runtime }}
        ensure: present
        comment: Application runtime user
        login: true
        superuser: false
        createdb: false
        createrole: false
        replication: false
        bypassrls: false
        passwordSecret:
          name: {{ include "controlplane-app.fullname" . }}-pg-runtime

  storage:
    storageClass: aws-gp3-daily-backup
    size: {{ .Values.postgres.cluster.storage.size }}

  certificates:
    serverTLSSecret: {{ include "controlplane-app.fullname" . }}-postgres-cert
    serverCASecret: {{ include "controlplane-app.fullname" . }}-postgres-cert

  resources:
    requests:
      cpu: {{ .Values.postgres.cluster.resources.requests.cpu }}
      memory: {{ .Values.postgres.cluster.resources.requests.memory }}
    limits:
      cpu: {{ .Values.postgres.cluster.resources.limits.cpu }}
      memory: {{ .Values.postgres.cluster.resources.limits.memory }}

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ include "controlplane-app.fullname" . }}-aws-s3-postgres-backup
