apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controlplane-app.fullname" . }}-postgres-backup-creds
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.postgres.backup.objectStore.credentials.accessKeyId | quote }}
  ACCESS_SECRET_KEY: {{ .Values.postgres.backup.objectStore.credentials.secretAccessKey | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "controlplane-app.fullname" . }}-pg-superuser
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  username: {{ .Values.postgres.users.superuser.name | quote }}
  password: {{ .Values.postgres.users.superuser.password | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "controlplane-app.fullname" . }}-pg-runtime
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  username: {{ .Values.postgres.users.runtime.name | quote }}
  password: {{ .Values.postgres.users.runtime.password | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "controlplane-app.fullname" . }}-pg-migration
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  username: {{ .Values.postgres.users.migration.name | quote }}
  password: {{ .Values.postgres.users.migration.password | quote }}
