apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controlplane-app.fullname" . }}-postgres-backup-creds
  {{- with .Values.postgres.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.postgres.backup.objectStore.credentials.accessKeyId | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ .Values.postgres.backup.objectStore.credentials.secretAccessKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "controlplane-app.fullname" . }}-pg-superuser
  {{- with .Values.postgres.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgres.users.superuser.name | b64enc | quote }}
  password: {{ .Values.postgres.users.superuser.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "controlplane-app.fullname" . }}-pg-runtime
  {{- with .Values.postgres.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgres.users.runtime.name | b64enc | quote }}
  password: {{ .Values.postgres.users.runtime.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "controlplane-app.fullname" . }}-pg-migration
  {{- with .Values.postgres.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    cnpg.io/reload: "true"
    {{- include "controlplane-app.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgres.users.migration.name | b64enc | quote }}
  password: {{ .Values.postgres.users.migration.password | b64enc | quote }}
