apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane.connectorStatusName" . }}-config"
  labels:
    {{- include "controlplane.selectorLabelsConnectorStatus" . | nindent 4 }}
data:
  config.toml: |-
    [connector_status]
    [connector_status.connector_status_repository]
    influxdb_org= "{{ .Values.connectorStatus.config.influxdb.org }}"
    influxdb_url= "{{ .Values.connectorStatus.config.influxdb.url }}"
    influxdb_token= "{{ .Values.connectorStatus.config.influxdb.token }}"

    [connector_status.app_endpoint]
    url   = "{{ .Values.connectorStatus.config.appEndpoint.url }}"
    token = "{{ .Values.connectorStatus.config.appEndpoint.token }}"

    [connector_status.kafka]
    bootstrap_servers = [{{- range .Values.connectorStatus.config.kafka.bootstrapServers }}"{{ . }}",{{- end }}]
    sasl_username     = "{{ .Values.connectorStatus.config.kafka.saslUsername }}"
    sasl_password     = "{{ .Values.connectorStatus.config.kafka.saslPassword }}"

    [connector_status.logger]
    level = "debug"
