apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane.connectorStatusName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  type: {{ .Values.connectorStatus.service.type }}
  ports:
  - port: {{ .Values.connectorStatus.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "controlplane.selectorLabelsConnectorStatus" . | nindent 4 }}
