apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-interface-sa
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.iotKafkaInterfaceCronjob.serviceAccount.roleArn }}"
automountServiceAccountToken: {{ .Values.iotKafkaInterfaceCronjob.serviceAccount.automount }}