apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "postgres.clusterName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- include "postgres.namespace" . | nindent 2 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: {{ .Values.cluster.instances }}
  description: {{ default (printf "%s Postgres Cluster" (include "postgres.fullname" .)) .Values.cluster.description | quote }}
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: {{ include "postgres.superuserSecretName" . }}

  bootstrap:
    initdb:
      database: {{ default (include "postgres.name" . | replace "-" "_") .Values.cluster.database }}
      owner: {{ default (printf "%s_user" (include "postgres.name" . | replace "-" "_")) .Values.cluster.owner }}
      secret:
        name: {{ include "postgres.superuserSecretName" . }}

  storage:
    storageClass: {{ default "aws-gp3-daily-backup" .Values.cluster.storage.storageClass }}
    size: {{ .Values.cluster.storage.size }}

  {{- if .Values.certificates.enabled }}
  certificates:
    serverTLSSecret: {{ include "postgres.certificateSecretName" . }}
    serverCASecret: {{ include "postgres.certificateSecretName" . }}
  {{- end }}

  {{- with .Values.cluster.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.cluster.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.objectStore.enabled }}
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ include "postgres.objectStoreName" . }}
  {{- end }}
