{{- if .Values.objectStore.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ include "postgres.objectStoreName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- include "postgres.namespace" . | nindent 2 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  configuration:
    destinationPath: {{ .Values.objectStore.destinationPath | quote }}
    s3Credentials:
      accessKeyId:
        name: {{ include "postgres.backupCredentialsSecretName" . }}
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: {{ include "postgres.backupCredentialsSecretName" . }}
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
{{- end }}
