{{- if and .Values.objectStore.enabled .Values.secrets.backupCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.backupCredentialsSecretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- include "postgres.namespace" . | nindent 2 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.secrets.backupCredentials.accessKeyId | quote }}
  ACCESS_SECRET_KEY: {{ .Values.secrets.backupCredentials.secretAccessKey | quote }}
---
{{- end }}
{{- if .Values.secrets.superuser.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.superuserSecretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- include "postgres.namespace" . | nindent 2 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secrets.superuser.username | quote }}
  password: {{ .Values.secrets.superuser.password | quote }}
{{- end }}
