apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "controlplane.authZName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.authZ.autoscaling.enabled }}
  replicas: {{ .Values.authZ.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "controlplane.selectorLabelsAuthZ" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.authZ.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "controlplane.selectorLabelsAuthZ" . | nindent 8 }}
        {{- with .Values.authZ.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.authZ.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "controlplane.serviceAccountAuthZName" . }}
      securityContext:
        {{- toYaml .Values.authZ.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.authZ.securityContext | nindent 12 }}
          image: "{{ .Values.authZ.image.repository }}:{{ .Values.authZ.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.authZ.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.connectorControl.service.gRPCPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.connectorControl.service.httpPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: v1/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: v1/health
              port: http
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: v1/ready
              port: http
            failureThreshold: 2
            periodSeconds: 30
          resources:
            {{- toYaml .Values.authZ.resources | nindent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/edged/
      volumes:
        - name: config-volume
          configMap:
            name: "{{ include "controlplane.authZName" . }}-config"
      {{- with .Values.authZ.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authZ.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authZ.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
