{{- $gatewayName := include "controlplane.fullname" . -}}
{{- $name := include "controlplane.authZName" . -}}
{{- $svcPort := .Values.authZ.service.httpPort -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $gatewayName }}-authz
  labels:
    authentication/zitadel: jwt
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
  hostnames:
  {{- range .Values.recordNames }}
    - {{ . }}
  {{- end }}
  rules:
  {{- range .Values.authZ.gatewayAPI.hosts }}
    - matches:
      {{- range .paths }}
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: GET
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: POST
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: DELETE
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: PATCH
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: PUT
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: OPTIONS
      {{- end }}
      backendRefs:
        - name: {{ $name }}
          port: {{ $svcPort }}
  {{- end }}

