{{- if .Values.frontend.ingress.enabled -}}
{{- $fullName := include "conference.frontend" . -}}
{{- $svcPort := .Values.frontend.service.port -}}
{{- if and .Values.frontend.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.frontend.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.frontend.ingress.annotations "kubernetes.io/ingress.class" .Values.frontend.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "conference.selectorLabelsFrontend" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.frontend.ingress.tls.clusterIssuer }}
  {{- with .Values.frontend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.frontend.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.frontend.ingress.hostname }}
      {{- range .Values.frontend.ingress.extraHosts }}
        {{- if .host }}
      -  {{ .host }}
        {{- end }}
      {{- end }}
      secretName: {{ .Values.frontend.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.frontend.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.path }}
            pathType: {{ $.Values.frontend.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- range .Values.frontend.ingress.extraHosts }}
    {{- if ne .host "" }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $.Values.frontend.ingress.path }}
            pathType: {{ $.Values.frontend.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
    {{- end }}
{{- end }}
