{{- $influxName := include "controlplane.name" . -}}
apiVersion: v1
data:
  admin-password: {{ include "controlplane.influxdb2.secrets.password" . }}
  admin-token: {{ include "controlplane.influxdb2.secrets.token" . }}
kind: Secret
metadata:
  name: {{ $influxName }}-influxdb2-auth
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
