apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roclub-connector-provisioning.fullname" . }}
  labels:
    {{- include "roclub-connector-provisioning.labels" . | nindent 4 }}
data:
  config.toml: |-
    [app]
    port = {{ .Values.frontend.config.app.port }}
    environment = "{{ .Values.frontend.config.app.environment }}"

    [kafka]
    bootstrap_servers = {{ .Values.backend.config.kafka.bootstrapServers }}
    sasl_username = "{{ .Values.backend.config.kafka.saslUsername }}"
    sasl_password = "{{ .Values.backend.config.kafka.saslPassword }}"
    subscription_topics = {{ .Values.backend.config.kafka.subscriptionTopics }}
    client_id = "{{ .Values.backend.config.kafka.clientID }}"
    group_id = "{{ .Values.backend.config.kafka.groupID }}"

    [mongodb]
    connection_string = "{{ .Values.backend.config.mongodb.connectionString}}"

    [logger]
    level = "{{ .Values.config.logger }}"
