apiVersion: v2
appVersion: v0.1.2
kubeVersion: ">=1.22.0-0"
version: 0.1.0

name: roclub-app-backend-org-registration
description: The Helm chart used to deploy the roclub app backend API
home: https://github.com/roclub/helm-charts
type: application