nameOverride: ""
fullnameOverride: ""
imagePullSecrets:
- name: docker
api:

  replicaCount: 1

  image:
    repository: ghcr.io/roclub/app-backend-org-registration-api 
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
    tls:
      hosts: []
      secretName: ""
      clusterIssuer: ""

  serviceAccount:
    create: true
    name: ""

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  config:
    http:
      port: 8080
      bearerToken: ""
    
    logger:
      level: "debug"


authority:

  config:
    repository:
      connectionString: ""
      database: ""
      collection: ""
    
    logger:
      level: "debug"