{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "conference.fullname" . -}}
{{- $svcPort := .Values.frontend.service.port -}}
{{- $stage := .Values.httpRoute.stage -}}
{{- $clientID := .Values.httpRoute.oidc.clientID -}}
{{- $clientSecret := .Values.httpRoute.oidc.clientSecret -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-oidc
  labels:
    {{- include "conference.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $fullName }}
  hostnames:
  {{- range .Values.httpRoute.tls.hosts }}
    - {{ . }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: 'PathPrefix'
            value: '/'
      backendRefs:
        - name: {{ $fullName }}-conference-frontend
          port: {{ $svcPort }}
---
{{- range .Values.httpRoute.tls.hosts }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $fullName }}-{{ . }}-oidc
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $fullName }}-oidc
  oidc:
    provider:
      issuer: "https://identity.{{ $stage }}.roclub.io"
    clientID:  "{{ $clientID }}"
    clientSecret: 
      name: "{{ $fullName }}-oauth-secret"
    redirectURL: "https://{{ . }}/oauth2/callback"
    logoutPath: "https://{{ . }}/"
    cookieDomain: "identity.{{ $stage }}.roclub.io"
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-oauth-secret"
data:
  client-secret: {{ $clientSecret }}
{{- end }}
