{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: {{ include include "roclub-app-backend.fullname" . }}
  labels:
    {{- include "roclub-app-backend.labels" . | nindent 4 }}
    {{ include "roclub-app-backend.labels-device-status" . }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    priority: 10
    match: Host(`{{ .Values.ingress.host }}`) && Path(`/api/v1/devices/status`)
    services:
    - name: {{ include "roclub-app-backend.fullname" . }}
      port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}