{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "roclub-app-backend.serviceAccountName" . }}
  labels:
    {{- include "roclub-app-backend.labels" . | nindent 4 }}
    {{ include "roclub-app-backend.labels-device-status" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
