imagePullSecrets:
- name: dockerconfigjson-github-com

nameOverride: ""
fullnameOverride: ""

stage: "dev"
recordNames:
- "conference-1.dev.roclub.io"
- "conference-2.dev.roclub.io"

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources: {}

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector:
  beta.kubernetes.io/arch: arm64 
tolerations: []
affinity: {}

httpRoute:
  enabled: true

image:
  repository: ghcr.io/roclub/livekit-remote-control-conference-development
  pullPolicy: Always
  
replicaCount: 1

service:
  type: ClusterIP
  port: 8080

