imagePullSecrets:
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

stage: "dev"

serviceAccount:
  create: true
  annotations: {}
  name: ""

  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

httpRoute:
  enabled: true
  stage: dev
  tls:
    secretName: "conference2-tls"
    hosts: 
    - "conference12.dev.roclub.io"
  oidc:
    clientID: "285637959913375059"
    clientSecret: Lm128lLLOW2AT1yqG4Cj2EmQTLdtJl5oDClWz13B7Ibd62bMqpixGxrlfsWnJ1vf

frontend:
  image:
    repository: ghcr.io/roclub/livekit-remote-control-conference-development
    pullPolicy: Always
    
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8080


  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
