apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane.notificationsName" . }}-config"
  labels:
    {{- include "controlplane.selectorLabelsNotifications" . | nindent 4 }}
data:
  config.toml: |-
    [notification]
    [notification.logger]
    level = "debug"
