{{- if .Values.notifications.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controlplane.serviceAccountNotificationsName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  {{- with .Values.notifications.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.notifications.serviceAccount.automount }}
{{- end }}
