replicaCount: 1

image:
  repository: harbor.mgt.roclub.io/roclub/roclub/knowledgebase
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
- name: harbor-pull-secret-roclub

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

cloudfront:
  enabled: true
  cachePolicyId: ""
  originRequestPolicyId: ""
  responseHeadersPolicyId: ""
  hostedZoneId: Z014743627GZM6VTA9N24
  additionalAliases: []
  
httpRoute:
  enabled: true
  stage: dev
  oidc:
    clientID: "285474337715194832"
    clientSecret: "kuwQhvfqxfMfwnK2jng3p7NTIcDwn2sEEh0z2iahaFMJtdJtrfQXJqqvEHVw0zZB"
  hosts:
    - knowledgebase-local.dev.roclub.io
    - origin-knowledgebase-local.dev.roclub.io

resources: {}

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
