nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

config:
  logger: "debug"

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

frontend:

  replicaCount: 1

  imagePullSecrets: []

  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    annotations: {}
    className: ""
    hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ""
              port:
                number: 80
    tls:
      hosts: []
      secretName: 
      clusterIssuer: 

    config:
      app:
        environment: ""
        port: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
