{{- $fullName := include "roclub-app-backend-connector-registration.configName" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "roclub-app-backend-connector-registration.labels" . | nindent 4 }}
data:
  config.toml: |-
    [gateway]
        [gateway.http]
        port = "{{ .Values.gateway.service.port }}"
        bearer_token = "{{ .Values.global.config.gateway.http.bearerToken }}"

        [gateway.kafka]
        bootstrap_servers = "{{ .Values.global.config.gateway.kafka.bootstrapServers }}"
        sasl_username = "{{ .Values.global.config.gateway.kafka.saslUsername }}"
        sasl_password = "{{ .Values.global.config.gateway.kafka.saslPassword }}"
        topics = "{{ .Values.global.config.gateway.kafka.topic }}"

        [gateway.roclubapp]
        url = "{{ .Values.global.config.gateway.roclubApp.url }}"
        token = "{{ .Values.global.config.gateway.roclubApp.token }}"
    
    [registration]
        [registration.mongodb]
        connection_string = "{{ .Values.global.config.registration.mongodb.connectionString }}"

    [logger]
    level = "{{ .Values.global.config.logger.level }}"