apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-operations-platform.singallingName" . }}
  labels:
    {{- include "remote-operations-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.signallingServer.service.type }}
  ports:
    - port: {{ .Values.signallingServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "remote-operations-platform.selectorLabelsSignallingServer" . | nindent 4 }}