nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

config:
  logger: "debug"

frontend:

  replicaCount: 1

  image:
    repository: "ghcr.io/roclub/app-connector-provisioning-frontend"
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []


  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
    className: ""
    hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
    tls:
      hosts: []
      secretName: ""
      clusterIssuer: ""

    config:
      app:
        environment: ""
        port: ""

backend:
  replicaCount: 1

  image:
    repository: "ghcr.io/roclub/app-connector-provisioning-provision_authority"
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  config:
    kafka:
      bootstrapServers: ""
      saslUsername: ""
      saslPassword: ""
      subscriptionTopics: ""
      clientID: ""
      groupID: ""
    mongodb:
      connectionString: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
