nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

config:
  logger: "debug"

frontend:

  replicaCount: 1

  image:
    repository: "ghcr.io/roclub/app-connector-provisioning-frontend"
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []


  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    annotations: {}
    className: ""
    hosts:
    - host: ""
      paths:
        - path: /api/v1/devices
          pathType: Prefix
          backend:
            service:
              name: ""
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ""
              port:
                number: 80
    tls:
      hosts: []
      secretName: 
      clusterIssuer: 

    config:
      app:
        environment: ""
        port: ""
        backendUrl: ""

backend:
  replicaCount: 1

  image:
    repository: "ghcr.io/roclub/app-connector-provisioning-provision_authority"
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 8080

  config:
    kafka:
      bootstrapServers: ""
      saslUsername: ""
      saslPassword: ""
      subscriptionTopics: ""
      clientID: ""
      groupID: ""
      autoOffsetReset: ""
      enableAutoCommit: ""
      securityProtocol: ""
      saslMechanisms: ""
      pollInterval: ""

    mongodb:
      connectionString: ""
      database: ""
      collection: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
