nameOverride: ""
fullnameOverride: ""

frontend:

  replicaCount: 1

  image:
    repository: "ghcr.io/roclub/app-connector-provisioning-frontend"
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []


  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: ""
    hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
    tls:
      hosts: []
      secretName: ""


backend:
  replicaCount: 1

  image:
    repository: "ghcr.io/roclub/app-connector-provisioning-provision_authority"
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []

  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  service:
    type: ClusterIP
    port: 80

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
