apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-app-nextjs
type: Opaque
stringData:
  auth_secret: "{{ .Values.appSecrets.authSecret.secretKey }}"
  zitadel_issuer: "{{ .Values.appSecrets.zitadelIssuer.secretKey }}"
  zitadel_client_id: "{{ .Values.appSecrets.zitadelClientId.secretKey }}"
  zitadel_client_secret: "{{ .Values.appSecrets.zitadelClientSecret.secretKey }}"
  nextauth_url: "{{ .Values.appSecrets.nextauthUrl.secretKey }}"
  zitadel_project_id: "{{ .Values.appSecrets.zitadelProjectID.secretKey }}"
  zitadel_base_url: "{{ .Values.appSecrets.zitadelBaseUrl.secretKey }}"
  conference_project_id: "{{ .Values.appSecrets.conferenceProjectID.secretKey }}"
  zitadel_sa_app_csm_user: "{{ .Values.appSecrets.zitadelSaAppCsmUser.secretKey }}"
  zitadel_sa_app_csm_secret: "{{ .Values.appSecrets.zitadelSaAppCsmSecret.secretKey }}"
  zitadel_sa_app_admin_user: "{{ .Values.appSecrets.zitadelSaAppAdminUser.secretKey }}"
  zitadel_sa_app_admin_secret: "{{ .Values.appSecrets.zitadelSaAppAdminSecret.secretKey }}"
  zitadel_sa_app_dispatcher_user: "{{ .Values.appSecrets.zitadelSaAppDispatcherUser.secretKey }}"
  zitadel_sa_app_dispatcher_secret: "{{ .Values.appSecrets.zitadelSaAppDispatcherSecret.secretKey }}"
  zitadel_sa_app_user_user: "{{ .Values.appSecrets.zitadelSaAppUserUser.secretKey }}"
  zitadel_sa_app_user_secret: "{{ .Values.appSecrets.zitadelSaAppUserSecret.secretKey }}"
  zitadel_sa_controlplane_user: "{{ .Values.appSecrets.zitadelSaControlplaneUser.secretKey }}"
  zitadel_sa_controlplane_secret: "{{ .Values.appSecrets.zitadelSaControlplaneSecret.secretKey }}"
  zitadel_sa_app_admin_user_id: "{{ .Values.appSecrets.zitadelSaAppAdminUserID.secretKey }}"
  zitadel_sa_app_dispatcher_user_id: "{{ .Values.appSecrets.zitadelSaAppDispatcherUserID.secretKey }}"
  zitadel_sa_app_user_user_id: "{{ .Values.appSecrets.zitadelSaAppUserUserID.secretKey }}"

