imagePullSecrets:
- name: dockerconfigjson-github-com
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

signallingServer:
  image:
    repository: ghcr.io/roclub/cloud-signaling-server-node-prod
    pullPolicy: IfNotPresent
    tag: "v0.1.1"
    
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "dev-traefik"
    annotations: {}
    hosts:
    - host: "signalling-server.dev.roclub.io"
      paths:
        - path: /
          pathType: Prefix
    tls:
      hosts: ["signalling-server.dev.roclub.io"]
      secretName: "signalling-server-tls"
      clusterIssuer: "dev.roclub.io"
    
  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

remoteOperator:
  image:
    repository: ghcr.io/roclub/cloud-webrtc-remote-control
    pullPolicy: IfNotPresent
    tag: "0.4.2"
    
  replicaCount: 1

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "dev-traefik"
    annotations: {}
    hosts:
    - host: "remote-operator.dev.roclub.io"
      paths:
        - path: /
          pathType: Prefix
    tls:
      hosts: ["remote-operator.dev.roclub.io"]
      secretName: "remote-operator-tls"
      clusterIssuer: "dev.roclub.io"
    
  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

env:
  - name: VITE_APP_SIGNALING_SERVER_URL
    value: ""
  - name: VITE_APP_SIGNALING_SERVER_TOKEN
    value: ""
  - name: VITE_APP_DATA_CHANNEL_LABEL
    value: ""
  - name: VITE_APP_ENV
    value: ""
  - name: VITE_APP_BUBBLE_WEBHOOK
    value: ""
  - name: VITE_APP_BUBBLE_BEARER
    value: ""
  - name: VITE_APP_GRPC_SERVER_URL
    value: ""