{{- if .Values.httpRoute.enabled -}}
{{- $stage := .Values.httpRoute.stage -}}
{{- $fullname := include "knowledgebase.fullname" . -}}
{{- range .Values.httpRoute.hosts -}}
apiVersion: aws.roclub.io/v1alpha1
kind: dnsrecord
metadata:
  name: {{ .host }}
spec:
  providerConfigName: {{ $fullname }}-dns-record
  recordName: {{ .host }}
  zoneName: {{ trimPrefix "." (mustRegexFind "\\.([[:alnum:].]*)" .host) }}.
  stage: {{ $stage }}
  loadBalancerSelector: {{ $fullname }}
---
{{- end -}}
{{- end -}}
