{{- if .Values.httpRoute.enabled -}}
{{- $fullname := include "knowledgebase.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "knowledgebase.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $fullname }}
  hostnames:
  {{- range .Values.httpRoute.hosts }}
    - {{ .host }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: 'PathPrefix'
            value: '/en-en/'
      backendRefs:
        - name: {{ $fullname }}-en
          port: {{ $svcPort }}
    - matches:
        - path:
            type: 'PathPrefix'
            value: '/de-de/'
      backendRefs:
        - name: {{ $fullname }}-de
          port: {{ $svcPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullname }}-oidc
  labels:
    {{- include "knowledgebase.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $fullname }}
  hostnames:
  {{- range .Values.httpRoute.hosts }}
    - {{ .host }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: RegularExpression
            value: 'handbook'
        - path:
            type: RegularExpression
            value: 'onboarding'
        - path:
            type: RegularExpression
            value: 'privacy_and_security/'
        - path:
            type: RegularExpression
            value: 'requirements'
      backendRefs:
        - name: {{ $fullname }}-en
          port: {{ $svcPort }}
    - matches:
        - path:
            type: RegularExpression
            value: 'handbook'
        - path:
            type: RegularExpression
            value: 'onboarding'
        - path:
            type: RegularExpression
            value: 'privacy_and_security/'
        - path:
            type: RegularExpression
            value: 'requirements'
      backendRefs:
        - name: {{ $fullname }}-de
          port: {{ $svcPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullname }}-tls-redirect
spec:
  parentRefs:
    - name: {{ $fullname }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
  {{- range .Values.httpRoute.hosts }}
    - {{ .host }}
  {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullname }}-oauth-callback
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $fullname }}
  hostnames:
  {{- range .Values.httpRoute.hosts }}
    - {{ .host }}
  {{- end }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /oauth2/callback
      filters:
      - type: URLRewrite 
        urlRewrite:
          path:
            type: ReplaceFullPath
            replaceFullPath: /en-en/
          statusCode: 302
{{- end -}}         
