{{- $fullname := include "knowledgebase.fullname" . -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ $fullname }}-oidc-zitadel
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $fullname }}-oidc
  oidc:
    provider:
      issuer: "https://identity.{{ .Values.httpRoute.stage }}.roclub.io"
    clientID: "{{ .Values.httpRoute.oidc.clientID }}"
    clientSecret: 
      name: "{{ $fullname }}-oauth-secret"
    redirectURL: "https://knowledgebase.{{ .Values.httpRoute.stage }}.roclub.io/oauth2/callback"
    logoutPath: "https://knowledgebase.{{ .Values.httpRoute.stage }}.roclub.io/"
---
apiVersion: v1
data:
  client-secret: {{ .Values.httpRoute.oidc.clientSecret }} 
kind: Secret
metadata:
  name: "{{ $fullname }}-oauth-secret"

