apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane.remoteControlName" . }}-config"
  labels:
    {{- include "controlplane.selectorLabelsRemoteControl" . | nindent 4 }}
data:
  config.toml: |-
    [session_control]
    env = "{{ .Values.remoteControl.config.env }}"
    service_accounts = {{ .Values.remoteControl.config.serviceAccounts }}
    
    [session_control.iot_dataplane]
    key    = "{{ .Values.remoteControl.config.iotDataplane.key }}"
    secret = "{{ .Values.remoteControl.config.iotDataplane.secret }}"

    [session_control.redis]
    enabled = {{ .Values.remoteControl.config.redis.enabled }}
    url = "{{ .Values.remoteControl.config.redis.url }}"
    username = "{{ .Values.remoteControl.config.redis.username }}"
    password = "{{ .Values.remoteControl.config.redis.password }}"
    db = {{ .Values.remoteControl.config.redis.db }}
    ttl_seconds = {{ .Values.remoteControl.config.redis.ttlSeconds }}
    negative_ttl_seconds = {{ .Values.remoteControl.config.redis.negativeTtlSeconds }}
    timeout_ms = {{ .Values.remoteControl.config.redis.timeoutMs }}
    max_retries = {{ .Values.remoteControl.config.redis.maxRetries }}

    [session_control.liveKit]
    key = "{{ .Values.remoteControl.config.liveKit.key }}"
    secret = "{{ .Values.remoteControl.config.liveKit.secret }}"
    host = "{{ .Values.remoteControl.config.liveKit.host }}"
    ttl = "{{ .Values.remoteControl.config.liveKit.ttl }}"

    [session_control.openfga]
    url = "{{ .Values.remoteControl.config.openfga.url }}"
    store_id = "{{ .Values.remoteControl.config.openfga.storeId }}"
    model_id = "{{ .Values.remoteControl.config.openfga.modelId }}"

    [session_control.cinify]
    api_url = "{{ .Values.remoteControl.config.cinify.apiUrl }}"
    api_key = "{{ .Values.remoteControl.config.cinify.apiKey }}"
    table_name = "{{ .Values.remoteControl.config.cinify.tableName }}"
    batch_size = {{ .Values.remoteControl.config.cinify.batchSize }}
    failed_count_threshold = {{ .Values.remoteControl.config.cinify.failedCountThreshold }}
    global_cooldown = "{{ .Values.remoteControl.config.cinify.globalCooldown }}"
    grace_period = "{{ .Values.remoteControl.config.cinify.gracePeriod }}"
    session_usage_ttl = "{{ .Values.remoteControl.config.cinify.sessionUsageTTL }}"

    [session_control.authz_service]
    address = "http://{{ include "controlplane.authZServiceName" . }}:{{ .Values.authZ.service.port }}"

    [session_control.logger]
    level = "{{ .Values.remoteControl.config.logger }}"

    [session_control.notification_service]
    address = "http://{{ include "controlplane.notificationsName" . }}:8080"
