apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane.remoteControlName" . }}-config"
  labels:
    {{- include "controlplane.selectorLabelsRemoteControl" . | nindent 4 }}
data:
  config.toml: |-
    [session_control]
    env: "dev"
    serviceAccounts: []
    
    [session_control.iot_dataplane]
    key    = "{{ .Values.remoteControl.config.iotDataplane.key }}"
    secret = "{{ .Values.remoteControl.config.iotDataplane.secret }}"

    [session_control.liveKit]
    key = "{{ .Values.remoteControl.config.liveKit.key }}"
    secret = "{{ .Values.remoteControl.config.liveKit.secret }}"
    host = "{{ .Values.remoteControl.config.liveKit.host }}"
    ttl = "{{ .Values.remoteControl.config.liveKit.ttl }}"

    [session_control.authz_service]
    address = "http://{{ include "controlplane.authZName" . }}:8080"

    [session_control.logger]
    level = "{{ .Values.remoteControl.config.logger }}"
