apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane.remoteControlGatewayName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  type: {{ .Values.remoteControlGateway.service.type }}
  ports:
  - port: {{ .Values.remoteControlGateway.service.gRPCPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.remoteControlGateway.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "controlplane.selectorLabelsRemoteControlGateway" . | nindent 4 }}
