{{- if .Values.remoteControlGateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controlplane.serviceAccountRemoteControlGatewayName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  {{- with .Values.remoteControlGateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.remoteControlGateway.serviceAccount.automount }}
{{- end }}
