{{- $gatewayName := include "controlplane.fullname" . -}}
{{- $name := include "controlplane.remoteControlName" . -}}
{{- $svcPort := .Values.remoteControl.service.httpPort -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $gatewayName }}-remote-control
  labels:
    authentication/zitadel: jwt
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
  hostnames:
  {{- range .Values.recordNames }}
    - {{ . }}
  {{- end }}
  rules:
  {{- range .Values.remoteControl.gatewayAPI.hosts }}
    - matches:
      {{- range .paths }}
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      {{- end }}
      backendRefs:
        - name: {{ $name }}
          port: {{ $svcPort }}
  {{- end }}

