---
{{- if .Values.influxdb2.ingress.enabled -}}
apiVersion: aws.roclub.io/v1alpha1
kind: dnsrecord
metadata:
  name: controlplane-influx
spec:
  providerConfigName: "controlplane-dns-record-influx"
  recordName: {{ .Values.influxdb2.ingress.recordName }}
  zoneName: {{ .Values.influxdb2.ingress.zoneName }}
  stage: {{ .Values.influxdb2.ingress.stage }}
{{- end -}}
