{{- $stage := .Values.stage }}
{{- $gatewayName := include "controlplane.name" . -}}
apiVersion: aws.roclub.io/v1alpha1
kind: dnsrecord
metadata:
  name: {{ .Values.recordName }}
spec:
  providerConfigName: controlplane-dns-record
  recordName: {{ .Values.recordName }}
  zoneName: {{ trimPrefix "." (mustRegexFind "\\.([[:alnum:].]*)" .Values.recordName) }}.
  stage: {{ $stage }}
  loadBalancerSelector: {{ $gatewayName }}
