{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "conference.fullname" . -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ $fullName }}-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        externalTrafficPolicy: Cluster 
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes.io/service-name={{ $fullName }}
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-name: {{ $fullName }}
          service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $fullName }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    namespace: envoy-gateway-system
    name: {{ $fullName }}-proxy-config
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $fullName }}-letsencrypt
spec:
  gatewayClassName: {{ $fullName }}
  listeners:
  {{- range .Values.httpRoute.tls.hosts }}
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      hostname: {{ . }}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ . }}-https
  {{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $fullName }}-letsencrypt
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    preferredChain: ""
    email: platformengineering@roclub.com
    privateKeySecretRef:
      name: {{ $fullName }}-letsencrypt
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: {{ $fullName }}
{{- end -}}
