apiVersion: v1
kind: Service
metadata:
  name: {{ include "roclub-app-webrtc-test.frontendName" . }}
  labels:
    {{- include "roclub-app-webrtc-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "roclub-app-webrtc-test.selectorLabelsFrontend" . | nindent 4 }}
