{{- if .Values.ingress.enabled -}}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.cluster.podsCidrBlocks }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: {{ .Values.cluster.name }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: {{ .Values.cluster.name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
spec:
  region: {{ .Values.cluster.awsRegion }}
  sshKeyName: {{ .Values.cluster.sshKeyname }}
  version: {{ .Values.cluster.version }}
  {{- if .Values.cluster.iamAuthenticatorConfig }}
  iamAuthenticatorConfig:
    mapRoles:
    - username: "kubernetes-admin"
      rolearn: "arn:aws:iam::172771008158:role/aws-reserved/sso.amazonaws.com/eu-central-1/AWSReservedSSO_AWSAdministratorAccess_2d1965435ebceb35"
      groups:
      - "system:masters"
  {{- end }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  region: {{ .Values.cluster.awsRegion }}
  network:
    vpc:
      cidrBlock: "10.10.1.0/19"
    subnets:
    # Public
    - availabilityZone: eu-central-1a
      cidrBlock: "10.10.1.0/28"
      id: "cluster-subnet-public-eu-central-1a"
      isPublic: true
    - availabilityZone: eu-central-1b
      cidrBlock: "10.10.1.16/28"
      id: "cluster-subnet-public-eu-central-1b"
      isPublic: true
    - availabilityZone: eu-central-1c
      cidrBlock: "10.10.1.33/28"
      id: "cluster-subnet-public-eu-central-1c"
      isPublic: true
    # Private
    - availabilityZone: eu-central-1a
      cidrBlock: "10.10.2.0/24"
      id: "cluster-subnet-private-eu-central-1a"
      isPublic: false
    - availabilityZone: eu-central-1b
      cidrBlock: "10.10.3.0/24"
      id: "cluster-subnet-private-eu-central-1b"
      isPublic: false
    - availabilityZone: eu-central-1c
      cidrBlock: "10.10.4.0/24"
      id: "cluster-subnet-private-eu-central-1c"
      isPublic: false
---
# Nodegroup low profile
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi1-pool-0
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: capi1-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: {{ .Values.cluster.name }}-pool-0
  namespace: {{ .Values.cluster.namespace }}
spec: {}
---
# Nodegroup high profile
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ .Values.cluster.name }}-pool-high-0
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: 4
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: {{ .Values.cluster.name }}-pool-high-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: {{ .Values.cluster.name }}-pool-high-0
  namespace: {{ .Values.cluster.namespace }}
spec: {}
{{- end }}