apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roclub-connector-registration.fullname" . }}-aws-credentials
  labels:
    {{- include "roclub-connector-registration.labels" . | nindent 4 }}
data:
  credentials: |-
    [development-terraform]
    aws_access_key_id = AKIASQOPUL2PEZ52I4Y2
    aws_secret_access_key = 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