apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roclub-connector-registration.fullname" . }}-aws-config
  labels:
    {{- include "roclub-connector-registration.labels" . | nindent 4 }}
data:
  config: |-
    [profile development-terraform]
    region = eu-central-1