apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "roclub-connector-registration.fullname" . }}-config"
  labels:
    {{- include "roclub-connector-registration.labels" . | nindent 4 }}
data:
  connector-registration-api.toml: |-
    [webserver]
    port = {{ .Values.api.service.port }}
    bearer_token = "{{ .Values.api.config.webserver.bearerToken }}"
    [aws_iot_core]
    access_key = "{{ .Values.api.config.aws.accessKey }}"
    access_secret = "{{ .Values.api.config.aws.accessSecret }}"
    [repository]
    mongodb_connection_string = "{{ .Values.api.config.repository.connectionString }}"
    mongodb_database = "{{ .Values.api.config.repository.database }}"

    [kafka]
    bootstrap_servers = [{{- range .Values.config.kafka.bootstrapServers }}"{{ . }}",{{- end }}]
    group_id = "{{ .Values.config.kafka.groupdID }}"
    auto_offset_reset = "latest"
    enable_auto_commit = false
    security_protocol = "SASL_SSL"
    sasl_mechanisms = "PLAIN"
    sasl_username = "{{ .Values.config.kafka.saslUsername }}"
    sasl_password = "{{ .Values.config.kafka.saslPassword }}"
    topics = [{{- range .Values.config.kafka.topics }}"{{ . }}",{{- end }}]
    poll_intervall = {{ .Values.config.kafka.pollIntervall }}

    [connector-status]
    [connector-status.config]
    roclub_connector_timeout = 60

    [connector-status.roclubapp]
    webhoook_endpoint = "{{ .Values.config.roclubApp.webhoookEndpoint }}"
    webhook_token = "{{ .Values.config.roclubApp.webhookToken }}"
    webhook_trigger_intervall = {{ .Values.config.roclubApp.webhookTriggerIntervall

    [logger]
    level = "{{ .Values.api.config.logger.level }}"
