apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "roclub-connector-registration.fullname" . }}-config"
  labels:
    {{- include "roclub-connector-registration.labels" . | nindent 4 }}
data:
  connector-registration-api.toml: |-
    [webserver]
    port = {{ .Values.api.service.port }}
    bearer_token = "{{ .Values.api.config.webserver.bearerToken }}"
    [aws_iot_core]
    access_key = {{ .Values.api.config.aws.accessKey }}
    access_secret = {{ .Values.api.config.aws.accessSecret }}
    [repository]
    mongodb_connection_string = "{{ .Values.api.config.repository.connectionString }}"
    mongodb_database = "{{ .Values.api.config.repository.database }}"
    [logger]
    level = "{{ .Values.api.config.logger.level }}"
