{{- if .Values.httpRoute.enabled -}}
{{- $stage := .Values.httpRoute.stage -}}
{{- $fullName := include "conference.fullname" . -}}
{{- range .Values.httpRoute.tls.hosts -}}
apiVersion: aws.roclub.io/v1alpha1
kind: dnsrecord
metadata:
  name: {{ . }}
spec:
  providerConfigName: conference-dns-record
  recordName: {{ . }}
  zoneName: {{ trimPrefix "." (mustRegexFind "\\.([[:alnum:].]*)" . ) }}.
  stage: {{ $stage }}
  loadBalancerSelector: {{ $fullName }}
---
{{- end -}}
{{- end -}}
