apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roclub-app-backend.fullname" . }}
  labels:
    {{- include "roclub-app-backend.labels" . | nindent 4 }}
    {{ include "roclub-app-backend.labels-device-status" . }}
data:
  connector-status.toml: |-
    [connector-status]

        [connector-status.config]
        roclub_connector_timeout = 60

        [connector-status.api]
        bearer_token = "{{ .Values.config.api.bearerToken }}"

        [connector-status.kafka]
        bootstrap_servers = "{{ .Values.config.kafka.bootstrapServers }}"
        group_id = "{{ .Values.config.kafka.groupdID }}"
        auto_offset_reset = "latest"
        enable_auto_commit = false
        security_protocol = "SASL_SSL"
        sasl_mechanisms = "PLAIN"
        sasl_username = "{{ .Values.config.kafka.saslUsername }}"
        sasl_password = "{{ .Values.config.kafka.saslPassword }}"
        topics = {{ .Values.config.kafka.topics }}
        poll_intervall = {{ .Values.config.kafka.pollIntervall }}

        [connector-status.repository]
        mongodb_connection_string = "{{ .Values.config.database.mongoDBConnectionString }}"
        mongodb_database = "roclub-connector"
        mongodb_collection = "status"

        [connector-status.roclubapp]
        webhoook_endpoint = "{{ .Values.config.roclubApp.webhoookEndpoint }}"
        webhook_token = "{{ .Values.config.roclubApp.webhookToken }}"
        webhook_trigger_intervall = {{ .Values.config.roclubApp.webhookTriggerIntervall }}

    [logger]
    level = "{{ .Values.config.logging.logLevel }}"