apiVersion: v1
kind: Service
metadata:
  name: {{ include "roclub-app-backend.fullname" . }}
  labels:
    {{- include "roclub-app-backend.labels" . | nindent 4 }}
    {{ include "roclub-app-backend.labels-device-status" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "roclub-app-backend.selectorLabels" . | nindent 4 }}
