apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane.connectorControlName" . }}-config"
  labels:
    {{- include "controlplane.selectorLabelsConnectorControl" . | nindent 4 }}
data:
  config.toml: |-
    [connector_control]
    env = "{{ .Values.connectorControl.config.env }}"
    service_accounts = {{ .Values.connectorControl.config.serviceAccounts }}
    
    [connector_control.iot_dataplane]
    key    = "{{ .Values.connectorControl.config.iotDataplane.key }}"
    secret = "{{ .Values.connectorControl.config.iotDataplane.secret }}"

    [connector_control.redis]
    enabled = {{ .Values.connectorControl.config.redis.enabled }}
    url = "{{ .Values.connectorControl.config.redis.url }}"
    username = "{{ .Values.connectorControl.config.redis.username }}"
    password = "{{ .Values.connectorControl.config.redis.password }}"
    db = {{ .Values.connectorControl.config.redis.db }}
    ttl_seconds = {{ .Values.connectorControl.config.redis.ttlSeconds }}
    negative_ttl_seconds = {{ .Values.connectorControl.config.redis.negativeTtlSeconds }}
    timeout_ms = {{ .Values.connectorControl.config.redis.timeoutMs }}
    max_retries = {{ .Values.connectorControl.config.redis.maxRetries }}
    tls_enabled = {{ .Values.connectorControl.config.redis.tls.enabled }}
    tls_insecure_skip_verify = {{ .Values.connectorControl.config.redis.tls.insecureSkipVerify }}
    tls_server_name = "{{ .Values.connectorControl.config.redis.tls.serverName }}"
    tls_ca_cert_path = "{{ .Values.connectorControl.config.redis.tls.caCertPath }}"
    tls_cert_path = "{{ .Values.connectorControl.config.redis.tls.certPath }}"
    tls_key_path = "{{ .Values.connectorControl.config.redis.tls.keyPath }}"

    [connector_control.authz_service]
    address = "http://{{ include "controlplane.authZServiceName" . }}:{{ .Values.authZ.service.port }}"

    [connector_control.logger]
    level = "debug"
