apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "controlplane.connectorControlName" . }}-config"
  labels:
    {{- include "controlplane.selectorLabelsConnectorControl" . | nindent 4 }}
data:
  config.toml: |-
    [connector_control]
    env: "{{ .Values.connectorControl.config.env }}"
    serviceAccounts: "{{ .Values.connectorControl.config.serviceAccounts }}"
    
    [connector_control.iot_dataplane]
    key    = "{{ .Values.connectorControl.config.iotDataplane.key }}"
    secret = "{{ .Values.connectorControl.config.iotDataplane.secret }}"

    [connector_control.authz_service]
    address = "http://{{ include "controlplane.authZName" . }}:8080"

    [connector_control.logger]
    level = "debug"
