{{- $gatewayName := include "controlplane.fullname" . -}}
{{- $name := include "controlplane.connectorControlName" . -}}
{{- $svcPort := .Values.connectorControl.service.httpPort -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $gatewayName }}-connector-control
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
  hostnames:
  {{- range .Values.connectorControl.gatewayAPI.hosts }}
    - {{ .host }}
  {{- end }}
  rules:
  {{- range .Values.connectorControl.gatewayAPI.hosts }}
    - matches:
      {{- range .paths }}
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      {{- end }}
      backendRefs:
        - name: {{ $name }}
          port: {{ $svcPort }}
  {{- end }}

